version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/unit-testing # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: unit-testing-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline # gets the project dependencies
      
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: unit-testing-{{ checksum "pom.xml" }}
      
      - run: mvn cobertura:cobertura
      
      - run:
          name: Upload coverage reports
          command: bash <(curl -s https://codecov.io/bash)
      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
          
      - store_test_results:
          path: ~/junit
      
      - store_artifacts:
          path: ~/junit         
      
      #- store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
      #    path: target/surefire-reports
      
      - run: mvn package -Dmaven.test.skip=true # package
      
      - store_artifacts: # store the uberjar as an artifact
          path: target/unit-testing-0.0.1-SNAPSHOT.jar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    
    
